title: A simple guide to Async Rust
description: A beginner-friendly guide to async for those already familiar with the Rust programming language.
theme: just-the-docs
livereload: true
mermaid: 
  version: "10.9.0"

url: https://trantorian1.github.io/async-rust-guide

aux_links:
  Repository: https://github.com/Trantorian1/notes-rust-async
